package com.forummanagement.model;
// Generated Jul 5, 2017 12:26:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer catId;
	private String catName;
	private String catDescription;
	private Set topics = new HashSet(0);

	public Category() {
	}

	public Category(String catName, String catDescription) {
		this.catName = catName;
		this.catDescription = catDescription;
	}

	public Category(String catName, String catDescription, Set topics) {
		this.catName = catName;
		this.catDescription = catDescription;
		this.topics = topics;
	}

	public Integer getCatId() {
		return this.catId;
	}

	public void setCatId(Integer catId) {
		this.catId = catId;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getCatDescription() {
		return this.catDescription;
	}

	public void setCatDescription(String catDescription) {
		this.catDescription = catDescription;
	}

	public Set getTopics() {
		return this.topics;
	}

	public void setTopics(Set topics) {
		this.topics = topics;
	}

}
