package com.forummanagement.model;
// Generated Jul 5, 2017 12:26:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post implements java.io.Serializable {

	private Integer postId;
	private Topic topic;
	private User user;
	private String postContent;
	private Date postDate;

	public Post() {
	}

	public Post(Topic topic, User user, String postContent, Date postDate) {
		this.topic = topic;
		this.user = user;
		this.postContent = postContent;
		this.postDate = postDate;
	}

	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getPostContent() {
		return this.postContent;
	}

	public void setPostContent(String postContent) {
		this.postContent = postContent;
	}

	public Date getPostDate() {
		return this.postDate;
	}

	public void setPostDate(Date postDate) {
		this.postDate = postDate;
	}

}
