package com.forummanagement.model;
// Generated Jul 5, 2017 12:26:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

	private Integer topicId;
	private Category category;
	private User user;
	private String topicSubject;
	private Date topicDate;
	private Set posts = new HashSet(0);

	public Topic() {
	}

	public Topic(Category category, User user, String topicSubject, Date topicDate) {
		this.category = category;
		this.user = user;
		this.topicSubject = topicSubject;
		this.topicDate = topicDate;
	}

	public Topic(Category category, User user, String topicSubject, Date topicDate, Set posts) {
		this.category = category;
		this.user = user;
		this.topicSubject = topicSubject;
		this.topicDate = topicDate;
		this.posts = posts;
	}

	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTopicSubject() {
		return this.topicSubject;
	}

	public void setTopicSubject(String topicSubject) {
		this.topicSubject = topicSubject;
	}

	public Date getTopicDate() {
		return this.topicDate;
	}

	public void setTopicDate(Date topicDate) {
		this.topicDate = topicDate;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

}
