package com.forummanagement.model;
// Generated Jul 5, 2017 12:26:32 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPass;
	private String userEmail;
	private Date userDate;
	private int userLevel;
	private Set topics = new HashSet(0);
	private Set posts = new HashSet(0);

	public User() {
	}

	public User(String userName, String userPass, String userEmail, Date userDate, int userLevel) {
		this.userName = userName;
		this.userPass = userPass;
		this.userEmail = userEmail;
		this.userDate = userDate;
		this.userLevel = userLevel;
	}

	public User(String userName, String userPass, String userEmail, Date userDate, int userLevel, Set topics, Set posts) {
		this.userName = userName;
		this.userPass = userPass;
		this.userEmail = userEmail;
		this.userDate = userDate;
		this.userLevel = userLevel;
		this.topics = topics;
		this.posts = posts;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public Date getUserDate() {
		return this.userDate;
	}

	public void setUserDate(Date userDate) {
		this.userDate = userDate;
	}

	public int getUserLevel() {
		return this.userLevel;
	}

	public void setUserLevel(int userLevel) {
		this.userLevel = userLevel;
	}

	public Set getTopics() {
		return this.topics;
	}

	public void setTopics(Set topics) {
		this.topics = topics;
	}

	public Set getPosts() {
		return this.posts;
	}

	public void setPosts(Set posts) {
		this.posts = posts;
	}

}
